apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::006423017798:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::006423017798:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DE5JOI782IQ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-23T21:03:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "910"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4e6a9164-57b9-49e5-810f-419bb1940e6e
