apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::006423017798:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DE5JOI782IQ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-03T18:41:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "948"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2b5bdb58-8195-495e-9459-1362fab8871c
