apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::006423017798:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1GDTETJ0BKAJ0
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::006423017798:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-10T19:53:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "869"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6e5bb2b5-6b18-4e42-bf04-c64973418ecf
