apiVersion: v1
data:
  mapRoles: |
  - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::006423017798:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-6TRUV7TVR0HB
      username: system:node:{{EC2PrivateDNSName}}
  - groups:
      - system:masters
      rolearn: arn:aws:iam::006423017798:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-09T08:07:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "912"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6d42fd69-171d-47fa-95f6-56aa2690f072
